/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import static clases.ListaPersona.listaPersona;
import clases.Persona;
import javax.swing.DefaultListModel;

/**
 *
 * @author santamaria
 */
public class ListarGP extends javax.swing.JFrame {
    //instanciamos un modelo que trae ya netbeans por default para de el imprimir en la interfaz sobre el objeto lista
    static private DefaultListModel miLista;

    /**
     * Creates new form ListarGP
     */
    public ListarGP() {  //constructor inicia, ubica y muestra la lista de usuarios
        initComponents();
        setLocationRelativeTo(null); 
        setListaGrafica();
        
    }
    
    

    //static private
       public void setListaGrafica() { //metodo para listar los usuarios creamos el objeto lista
        if (jlisListaUsu==null) {      //luego cargamos los datos en una variable y poder añadirlos en el orden deseado
            return;                    // a la variable instanciada de lista default y finalmente a el objeto lista
        }

        miLista = new DefaultListModel();
        for (Persona persona : listaPersona) {
            String datos=("Nombre:"+persona.getNombre()+" Cedula:"+persona.getNacionalidad()+persona.getCedula()+" EDAD:"+persona.getEdad());
            miLista.addElement(datos);
            
        }

        jlisListaUsu.setModel(miLista);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTlistausua = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlisListaUsu = new javax.swing.JList();
        jlListaI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(430, 510));
        setMinimumSize(new java.awt.Dimension(430, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        jlTlistausua.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jlTlistausua.setText("LISTA DE USUARIOS");
        getContentPane().add(jlTlistausua);
        jlTlistausua.setBounds(111, 11, 201, 37);

        jScrollPane1.setViewportView(jlisListaUsu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(37, 66, 358, 408);

        jlListaI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/im1.jpg"))); // NOI18N
        getContentPane().add(jlListaI);
        jlListaI.setBounds(0, 0, 430, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarGP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarGP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarGP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarGP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarGP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlListaI;
    private javax.swing.JLabel jlTlistausua;
    private static javax.swing.JList jlisListaUsu;
    // End of variables declaration//GEN-END:variables
}
