/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.ListaPersona;
import clases.Persona;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author santamaria
 */
public class Registrarp extends javax.swing.JFrame {

    /**
     * Creates new form Registrarp
     */
    public Registrarp() { //iniciando componentes de la venta y ubicando en el centro
        initComponents();
        setLocationRelativeTo(null);

    }

    private void setDefaults() { //metodo para resetear las opciones luego de registrar
        tfNombre.setText("");
        cbVenExt.setSelectedIndex(0);
        tfCedula.setText("");
        spEdad.setValue(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jltNombre = new javax.swing.JLabel();
        jltCedula = new javax.swing.JLabel();
        jltEdad = new javax.swing.JLabel();
        cbVenExt = new javax.swing.JComboBox();
        jbRegistrar = new javax.swing.JButton();
        jbLista = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfCedula = new javax.swing.JTextField();
        spEdad = new javax.swing.JSpinner();
        jlREG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(506, 409));
        setMinimumSize(new java.awt.Dimension(506, 409));
        setPreferredSize(new java.awt.Dimension(506, 409));
        setResizable(false);
        getContentPane().setLayout(null);

        jlTitulo.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jlTitulo.setText("REGISTRAR DATOS DE PERSONA");
        getContentPane().add(jlTitulo);
        jlTitulo.setBounds(100, 30, 330, 30);

        jltNombre.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jltNombre.setText("NOMBRE");
        getContentPane().add(jltNombre);
        jltNombre.setBounds(30, 110, 90, 30);

        jltCedula.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jltCedula.setText("CEDULA");
        getContentPane().add(jltCedula);
        jltCedula.setBounds(30, 170, 100, 20);

        jltEdad.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jltEdad.setText("EDAD");
        getContentPane().add(jltEdad);
        jltEdad.setBounds(50, 220, 60, 40);

        cbVenExt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbVenExt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "E" }));
        cbVenExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVenExtActionPerformed(evt);
            }
        });
        getContentPane().add(cbVenExt);
        cbVenExt.setBounds(130, 163, 40, 20);

        jbRegistrar.setBackground(new java.awt.Color(51, 255, 255));
        jbRegistrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbRegistrar.setText("REGISTRAR");
        jbRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(jbRegistrar);
        jbRegistrar.setBounds(70, 300, 160, 50);

        jbLista.setBackground(new java.awt.Color(102, 255, 255));
        jbLista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbLista.setText("LISTA");
        jbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbListaMouseClicked(evt);
            }
        });
        getContentPane().add(jbLista);
        jbLista.setBounds(290, 300, 150, 50);

        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });
        getContentPane().add(tfNombre);
        tfNombre.setBounds(130, 110, 310, 20);

        tfCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(tfCedula);
        tfCedula.setBounds(180, 160, 260, 20);

        spEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spEdad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        getContentPane().add(spEdad);
        spEdad.setBounds(130, 220, 40, 20);

        jlREG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/im1.jpg"))); // NOI18N
        jlREG.setMaximumSize(new java.awt.Dimension(506, 409));
        jlREG.setMinimumSize(new java.awt.Dimension(506, 409));
        jlREG.setPreferredSize(new java.awt.Dimension(506, 409));
        getContentPane().add(jlREG);
        jlREG.setBounds(0, 0, 510, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbVenExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVenExtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVenExtActionPerformed

    private void jbRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegistrarMouseClicked
        // TODO add your handling code here:

        //Evento del boton que donde instanciamos, creamos, añadimos a la lista un usuario y reseteamos las opciones
        Persona persona = new Persona(tfNombre.getText(), (String) cbVenExt.getSelectedItem(), Integer.parseInt(tfCedula.getText()), (int) spEdad.getValue());

        ListaPersona.addPersona(persona);
        JOptionPane.showMessageDialog(null,
                "SU USUARIO "
                + tfNombre.getText()
                + " SE REGISTRO SATISFACTORIAMENTE"
        );
        setDefaults();


    }//GEN-LAST:event_jbRegistrarMouseClicked

    private void jbListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbListaMouseClicked
        // TODO add your handling code here:

        //instanciamos la ventana de listar para asi llamarla y volverla visible
        ListarGP f = new ListarGP();
        f.setVisible(true); 


    }//GEN-LAST:event_jbListaMouseClicked

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        // TODO add your handling code here:
       //validamos solo texto en nombre
        char tecla;
        tecla = evt.getKeyChar();
        if (!Character.isLetter(tecla) && tecla != KeyEvent.VK_SPACE && tecla != KeyEvent.VK_BACKSPACE) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"SOLO PUEDE INTRODUCIR LETRAS");

        }

    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCedulaKeyTyped
        // TODO add your handling code here:
        //validamos solo numeros en cedula
        char tecla;
        tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACKSPACE) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"SOLO PUEDE INTRODUCIR NUMEROS");
        }

    }//GEN-LAST:event_tfCedulaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbVenExt;
    private javax.swing.JButton jbLista;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JLabel jlREG;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jltCedula;
    private javax.swing.JLabel jltEdad;
    private javax.swing.JLabel jltNombre;
    private javax.swing.JSpinner spEdad;
    private javax.swing.JTextField tfCedula;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

  //  private void ListarGP() {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
